version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:16.13-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run linting
      - run:
          command: yarn run test
          name: Run tests

workflows:
  version: 2
  run_test:
    jobs:
      - test:
          context:
            - "Docker Hub"
