version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test:
    docker:
      - image: cimg/node:16.13-browsers
    steps:
      - checkout

      - node/install:
          install-yarn: true

      - node/run:
          yarn-run: lint

      - node/run:
          yarn-run: test

workflows:
  version: 2
  test:
    jobs:
      - test
