version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.13-browsers
        environment:
          JOBS: 1
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  test:
    jobs:
      - test
